### ISSUE TITLE
UMW error and correction factors

### ISSUE THREAD

**Issue by jpeters7** [PalEON-Project/PLS_products#1]
@paciorek @Kah5 - the UMW code is ready to go and the raw data are now on the wiki ([](https://paleon.geography.wisc.edu/doku.php/data_and_products;settlement_vegetation)).

When I ran through the UMW code, the only issue I found was on line 723:
"nwmw@data[(is.na(nwmw$SP1) & nwmw$DIAM1>0) | (is.na(nwmw$SP2) & nwmw$DIAM2>0),] <- rep(NA, ncol(nwmw))  #  removes four records with no identified trees, but identified diameters"

I got an error that said: missing values are not allowed in subscripted assignments of data frames.
Could you guys look at this when you run the code?

@Kah5 there is a note under the UMW data that we need the correction factors. Do you have those or do I need to work with Simon to find them?  I imagine they are in his GitHub repo, we just have to find them.

**Comment by SimonGoring** [comment]
That seems to be an issue that somehow there's an NA being returned from that boolean, but I'm surprised.  Is there not a call that replaces the is.na DIAM variables with 0?  That's likely the issue, see which DIAMs have NAs.

The correction tables is in [data/input/relation_tables](https://github.com/PalEON-Project/WitnessTrees/blob/master/data/input/relation_tables/cogbill_corrections.csv) in the [WitnessTrees repository](https://github.com/PalEON-Project/WitnessTrees)

**Comment by Kah5** [comment]
I have added the correction factors for IN, IL, and so. Michigan to the table. I have that. Should i push it to github or send to jody? What should the version be?

Kelly

**Comment by paciorek** [comment]
Let's put the file onto the Wiki with a version number to be chosen by Jody.

**Comment by Kah5** [comment]
Okay, I will send it to jody to put on the wiki.

**Comment by jpeters7** [comment]
correction factors file is on the wiki!  
@SimonGoring on line 716, I tried adding: 
nwmw$DIAM1[is.na(nwmw$DIAM1)] <- 0
nwmw$DIAM2[is.na(nwmw$DIAM2)] <- 0

But even after doing that I still got the Error and Warning messages:
Error in `[<-.data.frame`(`*tmp*`, (is.na(nwmw$SP1) & nwmw$DIAM1 > 0) |  : 
  missing values are not allowed in subscripted assignments of data frames
In addition: Warning messages:
1: In Ops.factor(nwmw$DIAM1, 0) : ‘>’ not meaningful for factors
2: In Ops.factor(nwmw$DIAM2, 0) : ‘>’ not meaningful for factors

After I ran this code on line 726
 nwmw@data[(is.na(nwmw$SP1) & nwmw$DIAM1>0) | (is.na(nwmw$SP2) & nwmw$DIAM2>0),] <- rep(NA, ncol(nwmw))  #  removes four records with no identified trees, but identified diameters

**Comment by jpeters7** [comment]
@Kah5 and I got this code to work:
nwmw@data[(is.na(nwmw$SP1) & nwmw$DIAM1>0) | (is.na(nwmw$SP2) & nwmw$DIAM2>0),] <- rep(NA, ncol(nwmw)) # removes four records with no identified trees, but identified diameters
