### ISSUE TITLE
remove IL and IN corners that overlap with UMW corners

### ISSUE THREAD

**Issue by jpeters7** [PalEON-Project/PLS_products#10]
Reminder for Jody to remove the IL and IN corners that overlap. There aren't many, but they should be cleaned up.

**Comment by jpeters7** [comment]
@paciorek I looked at the corners on the IL/WI and IN/MI borders and wanted to get your input on what I'm finding. For IN/MI the points do not overlap on top of each other. But the townships are narrow so there is about a half of a township amount of space in IN on the west side of the state. Image 1 below (yellow/green dots = IN corners, pink dots = MI corners) shows where the western township (outlined in red) has IN points that are 40 chains from the adjacent corner to the south but because the townships are not aligned, these corners fall on the border in between the MI corners.  As you go east along the border in image 1, the townships get narrower to the point where we no longer have the standard 40 chains in between corners and so we didn't include the corner that was on the border.   Image 2 is from the eastern part of IN where the townships are very narrow and the corners density increases.     
Image 1
![image](https://user-images.githubusercontent.com/6137819/37979562-e061808e-31b6-11e8-96c8-058b7bbee4b7.png)
Image 2
![image](https://user-images.githubusercontent.com/6137819/37979734-5a29ec58-31b7-11e8-8375-1252f918a8a1.png)
Do you think we want to remove the top row of IN corners to give more spacing between the corners?

For the IL/WI border I think we do want to remove the top row of corners from IL. While in images 3, 4 and 5 the IL corners (yellow/green corners) do not physically overlap the WI corners (red corners), they are closer together and line up on more as compared to the IN/MI corners where the IN corners are often like the 1/4 section corners (corners that are mid-way between where the sections intersect) to the MI section corners (corners that fall where the sections intersect). In image 3, the green IL corner has no trees, the adjacent WI corner also has no trees.  While the other WI/IL corners that do have trees don't have the exact same trees/diameters/distances, they are often very similar and at all the corners but one all the trees are oaks.  
Because the WI/IL corners overlap to a greater degree, I think we should remove the IL corners. I can add code to remove the IL trees.  Then let me know what you think about the IN/MI trees.
@paciorek if it would be easier to walk through this on zoom we can do that tomorrow or Thursday.
Image 3
![image](https://user-images.githubusercontent.com/6137819/37980419-1a1015b4-31b9-11e8-818e-6ae9be66466d.png)
Image 4
![image](https://user-images.githubusercontent.com/6137819/37980523-5344e47c-31b9-11e8-813f-b32cc0c3e64d.png)
Image 5
![image](https://user-images.githubusercontent.com/6137819/37980913-42b7ceac-31ba-11e8-84a7-a0441f94ebcc.png)

**Comment by paciorek** [comment]
I think we want to remove points if we think they are duplicates and not if we think they aren't. It sounds like for WI/IL you think they are duplicates while for MI/IN, you think they are not. I'm not all that concerned about having some points that are closer together than is usual if we think they points are not duplicates.

**Comment by jpeters7** [comment]
Except for the one corner on the IL/WI border where there are both not trees because of water, these aren't duplicate corners. They do not have the same tree data. The corners are oak at Level3, but in some cases, they have different oaks at Level1 (black/burr vs white, etc) and in all cases, they have different diameters and distances.  o if you are not concerned about having points that are closer together, then we should leave them all in.

**Comment by paciorek** [comment]
Oh, I see. Well if they are that close together as in IL/WI, I agree with the idea of removing them, so please do that.

**Comment by jpeters7** [comment]
Added code to remove the 18 IL corners (in 3 townships) that are closely adjacent (<165 m) from the WI corners on the IL-WI border.
