### ISSUE TITLE
removing 99th percentile of density

### ISSUE THREAD

**Issue by Kah5** [PalEON-Project/PLS_products#11]
In UMW code, very high density points (>99th percentile) are replaced by the 99th percentile of all points. When we add the lower midwest, this changes the value of the 99th percentile. We should talk with @SimonGoring @paciorek about whether we want to use the 99th percentile of all the data for this, and get slightly different estimates for UMW than reported in the Witness Trees paper, or do we use the 99th percentile of the UMW data as our cut off for this?

**Comment by paciorek** [comment]
I wonder if a better way to do this is to try to get an expert-informed value for the highest possible density that could be supported considering only trees > 20 cm dbh. 

I.e., we have the problem that trees very close to the corner produce very high densities. But given we are considering only trees > 20 cm, there is probably some forestry-based result about the highest stocking you could get with trees that are about 20 cm. Obviously if trees are bigger the density is lower, so we would assume in this case that the local stand is an even-age stand of 20 cm trees.

@SimonGoring @Kah5 @jpeters7 what do you think? I suspect Charlie could come up with something fairly readily. Or Ben Poulter might be able to give us an idea of what the value would be.

**Comment by paciorek** [comment]
I'm responding to this comment (which appeared in my email but not in this Github thread):
"I'm sure we could, but it would be based on modern values, and (one) point of the paper was that modern values do not reflect the historical state."
but not sure who 'ringbailwanton' is (Simon?)

Ok, that's a good thing to consider, but max stocking is more of a biological constraint and not a property specific to a time period.

My concern is that any percentile of the estimated densities is arbitrary and that as a tree gets closer to the corner, the densities get higher and higher and at some point become unrealistic but the percentiles don't really get at the point at which things become unrealistic.

**Comment by paciorek** [comment]
@Kah5 says that 1000 trees/ha is about the 99th percentile. Most are less than 600-700 / hectare.

To discuss reasonable upper bound with Charlie.

**Comment by paciorek** [comment]
Based on discussion with Charlie 1000 trees / ha is very dense but not unbelievable. Look at empirical distribution but this may be a reasonable upper bound.

**Comment by paciorek** [comment]
For now when we calculate density *at a point* we truncate to 10,000 trees/ha. This of course then gets averaged out with all the other points in a cell and then statistically smoothed. 

Choice of 10,000 is to avoid huge outliers that have big influence but acknowledge that since each point estimate is known to be noisy we don't want to bias things by truncating high values when we are not similarly treating low values.
