### ISSUE TITLE
trees at distance 0 are only considered when they are tree #1

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#15]
This code sets azimuth to zero when dist is 0, but only does it for tree1. Why are we not doing it for tree2, tree3, tree4. Some of these have dist =0.
```
treed.center <- (dists[,1] == 0 & !is.na(azimuths[,1]) & diams[,1] > 0)
treed.center[is.na(treed.center)] <- FALSE
azimuths[treed.center,1] <- 0 #assign azimuth to 0
```

**Comment by jpeters7** [comment]
We should be doing this for tree 2 and 3. I don't think there are any 0 distance trees for tree 4, but it would still be good to include the code for tree 4 in case this situation comes up in the future as more IL and IN data are added.
Also if the 0 distance tree is for tree 1 or tree 3 and there are 2 other trees with distances listed for those corners, then we should include those corners and calculate the density using the 2 trees with distances, like we normally do.
If we have two trees and one is a 0 distance tree, then perhaps we can use the other tree with the distance, if we decide we can calculate density from just one tree.
If we only have one tree with 0 distance at a corner, I think we should make this corner NA (see my comments in issue #5

**Comment by paciorek** [comment]
Ok, thanks, I can modify the code to treat 0-distance trees the same.

I'm not following your idea to use the non-0-distance trees for density. Throwing away the 0-distance tree will presumably bias our density estimate downwards (though of course we also know that including it would result in an Infinity estimate). I think any case where we have a 0-distance tree is one where we need to substitute some upper bound on density.

**Comment by jpeters7** [comment]
Yeah. The 0-distance tree is tough. I like substituting an upper bound.  Probably would be good to run it by Charlie when we talk to him about the 1 tree->0 distance points.

**Comment by Kah5** [comment]
I think this code would work/was intended to work if it were implemented after sorting trees by distance. In theory, we shouldn't have two trees of dist == 0, but if you implement this code after sorting the trees, then it should set all azimuths = 0

**Comment by paciorek** [comment]
We are leaving 0-distance trees in an truncating the density at some reasonable upper bound.

**Comment by paciorek** [comment]
And confirmation from Charlie of our previous decision:

Your memory was good.  Although not exact, if one distance is 0 with a second >0, assume the 0 as a very short distance ~0 and use both as input into the inverse of the sum of squares in the Morisita 2-tree equation.  This all might get squirrely if the 0 is a soft 0 (missing or transcription error), but let's not fret and go ahead with the data as stated.
Also, make sure this is not applied to true 1-tree corners (as the 2-tree with one 0 and 1-tree designs appear very similar, especially if a tree is exactly at the corner) which are truly intractable in Morisita equation.
