### ISSUE TITLE
Wiki has UMW data after processing through 1_clean_merge_point_data.R  

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#2]
But I think our goal has been to have the individual MN, WI, upper MI data from Simon on the Wiki and then uppermidwest.coords_v1.csv will be an _intermediate_ file, not an input data file to the PLS data processing workflow.

@jpeters7 please advise. In particular I'd like to have the individual state files posted on the Wiki so I can do a code check of the point_processing code files starting from the very start.

**Comment by jpeters7** [comment]
I have removed the uppermidwest.coords_v1.csv from the wiki and uploaded the correct raw data for MN (Minnesota.shp), WI (glo_corn.shp), and MI (michigan_filled.shp).

**Comment by paciorek** [comment]
Can you version either the zip file?  I suppose we might version each individual state, but we probably won't be in the situation of having a lot of updates to individual states and we'd then need to change file names of multiple files, so maybe just the zip is sufficient.

Also for cleanness, can you remove the .gitignore files in each subdirectory?

**Comment by jpeters7** [comment]
I like versioning the zip file. We shouldn't be changing the individual state data, except through the R cleaning and merging code.
I added the version number to the zip file and I removed the .gitignore files from the subdirectories and pushed back to the wiki.
