### ISSUE TITLE
NA values in sp1 in No MI are excluded 

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#21]
We have ~10 cases where the code removes No MI points with NA as species1 but there are non-NA values for sp2, sp3, or sp4. Given that the distances are not yet ordered at this point, I'm not sure of the logic in only checking the sp1 case. 

Also we should check with @SimonGoring or Charlie about these NA cases if we use no tree points. Do we think no tree points in No MI are realistic?

**Comment by Kah5** [comment]
If the cases have a non- zero or non-NA value for the distance, then I think we can assume that these are "Unknown tree", but if dist == 0, then we should ask Charlie/Simon

**Comment by paciorek** [comment]
This now coincides with issue #29

**Comment by paciorek** [comment]
Closing given issue #29
