### ISSUE TITLE
level0_to_level3a_v0.4-7.csv missing "No tree" for Illinois

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#23]
@jpeters7  not sure why we didn't catch this, but we're missing a 'no tree' row for Illinois.

**Comment by jpeters7** [comment]
Glad you caught this!  When  I updated the conversion file for IL, I just summarized the trees. We're also missing the No data and Water and Wet entries.  I'll add both and update the counts for both IL and IN in the conversion file.

**Comment by jpeters7** [comment]
Updated and level0_to_level3a_v0.4-8.csv has been pushed to GitHub and the file name has been updated in the config file.
