### ISSUE TITLE
we need MN_surveys.csv file on Wiki

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#28]
@jpeters7 formerly this file was in the zip that contained the shapefile. We still need it. Not sure if you want to put it in the new minnesota zip file or have it as its own file on the Wiki. Perhaps the zip is the right place so we don't have to also version the MN_surveys.csv file?

**Comment by jpeters7** [comment]
I renamed to mn_surveys.csv and put it in with the mn_pls_projected_v1.1.zip file on the wiki. I also updated the config file to list mn_surveys.csv instead of MN_surveys.csv
