### ISSUE TITLE
where are line trees screened out?

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#3]
We should discuss where screening of line trees and similar screening is done? I would think we want it done in this repo, but not sure how hard it would be to push that processing to this repo, particularly for UMW.

I.e., it would probably be nice to have the processing start with what is truly the raw data. 

Apart from screening out line trees, is there other preprocessing being done to the data before processing done in this repo?

**Comment by jpeters7** [comment]
We should not have any line trees in IN, IL and southern Michigan. @SimonGoring are there line trees in the UMW data?

**Comment by paciorek** [comment]
Is that because those transcribing from the original records did not mark them down electronically?

**Comment by jpeters7** [comment]
For IL and IN that is the case - it was taking too long to add the extra information that we weren't planning to use.  For southern Michigan, I removed anything that looked like line trees from the original southern Michigan file that Simon sent.

**Comment by paciorek** [comment]
Jody removed the line trees by hand in GIS. 

Jody is checking on line trees in UMW.

**Comment by jpeters7** [comment]
From a check of the WI data, it appears we have all 1/4 section and section corners. No line trees.  There are a few places where townships do not line up, so there are "extra" corners that are entered for the north border of one township and the south border of another township.  Here is an example of how townships can be weird with sections that are not always evenly spaced (if the image comes through on GitHub...). We see this same sort of thing in all the domains.
![image](https://user-images.githubusercontent.com/6137819/37917306-0f52199c-30ec-11e8-96c7-e121d823eabb.png)

**Comment by paciorek** [comment]
Ok, so seems like we are ok on this in general.
