### ISSUE TITLE
how to treat water consistently

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#35]
In IN/IL, water/wet is only recorded for first tree and we throw out these points.

In southern MI @Kah5 mentioned in issue #6 that there was only one "water" case. Presumably points were thrown out previously somehow?

In northern MI, I don't see any cases of "water". So it would be good to know what criteria were used to omit water points.

In MN and WI we have a lot of points with some "water".
22926 have all water
1722 have one real tree
23129 have two real trees
1115 have three real trees

@SimonGoring mentioned in his code that: 
```
#  We need to indicate water and remove it.  There are 43495 cells with 'water'
#  indicated, and another 784 cells with 'missing' data.
#  when we limit these to the first two columns of the species table we get
#  a total of 25416 samples removed.
```
so it seems he wanted to keep cases with only 1-2 "trees" that are water, but I can't see in step.one.clean.bin_v1.4.R where this is actually done. 

@jpeters7 @Kah5 Thoughts? Should we confer with Charlie and Simon again? Given that you already have a procedure for IL/IN that produces water info only being present for first tree, perhaps we should be trying to make sure UMW is treated similarly.

**Comment by jpeters7** [comment]
Yes, we should check in with Simon and Charlie.  The one water entry in southern Michigan was listed as "creek" for sp2 and had diameter, quad, azimuth and distance data. Plus there was a basswood listed so I don't think that was a water location.  I assume for southern and northern Michigan the water areas were not entered in the data base because these data came from mylar maps that marked the trees at each corner.
@SimonGoring can you give us more insight into how "water" in Michigan and the Upper Midwest was treated?

**Comment by paciorek** [comment]
@jpeters7 how was 'water' in IN/IL determined?  Were cases with some water but 1, 2, or 3 trees present marked as water/wet for the first tree?

**Comment by jpeters7** [comment]
There are no trees at corners marked water or wet. Corners were marked "Water" if the notes said something like "corner in creek" or "corner in lake" or if the corner could not be set because of a water feature (lake, pond, swamp, creek, river, etc). Wet features are ones with notes that indicate the area was seasonally wet or where the notes say "wet prairie", "wet ground", etc.   
If the post is set in a water feature, but trees are noted, then we record the trees at those corners for trees 1,2,etc and put the water feature description in ecotype notes or general notes.

**Comment by paciorek** [comment]
Ok, that suggests that for UMW we should use the data if there are any trees.

A general concern for IL/IN or UMW is that density estimates may be biased low for such points because some of the area is in water and doesn't support trees, so the surveyors are selecting trees from only the (partial) area with trees. 

We probably want to exclude cases that have only one tree because of water but not sure how to do this and retain the cases where there is one tree because it is prairie. In other words, in UMW, the taxon info tells us that there is one tree and the rest is water. But in IL/IN, I think all we can easily determine without looking at the notes is that there is one tree. We don't know if that is because of water.

**Comment by jpeters7** [comment]
For IL/IN, if there is 1 tree and we want to make sure that it wasn't because there was water around, we would want to look at the ecotype notes to see if any water features are listed.  If there is water in the notes, it will be listed in Ecotype. If you want to move forward using the Ecotypes to assess the 1 tree points, I have a conversion file for the Ecotypes that converts the Ecotype single letters (e.g., L = Lake, P = Prairie, E = Field, etc).

**Comment by paciorek** [comment]
Running notes:

In WI, there are 4089 points with water but water is only marked for tree 1 and in essentially all cases no info is given for the other trees. 

So we throw out those WI points and any MN points with 4 cases of 'water'. For consistency with IL/IN we keep the MN points with 3 cases of 'water'.

**Comment by paciorek** [comment]
Summary for 4/26/18 call:

Discuss whether UMW, soMI match the IL/IN treatment that points with <4 trees and some water are all included in the raw data? What do we do with points that have water and might bias density low? Do we treat watery points with 1 vs 2 trees differently?

**Comment by paciorek** [comment]
Can't estimate with one tree and water. Throw out these points.

**Comment by paciorek** [comment]
Decision as follows:
If have >=2 trees, just estimate density and biomass and live with bias to lower density/biomass.
If have 1 tree and water, can't estimate density anyway and presumably these points are mostly water, so discard.

**Comment by paciorek** [comment]
Almost all IN/IL 1-tree points do _not_ have ecotype info, so can't separate out the wet points and will have to live with downward bias in density estimation in those states. There are 4140 IN/IL 1-tree points.

There are 877 southern MI 1-tree points. About 1/3 of these have something in 'notes', but essentially no indication there of water. Same conclusion as for IL/IN.

1714 points in MN with 1 tree and 3 water. Code is now excluding these.

4443 1-tree points in WI. About 1/4 of these have 'notes' values, but only a small number indicate water.  However, there is a vegtype for all of these:
```
  2    3    4    5    7    8    B    E    F    G    H    I    K    L    M    N 
 187   22   14   81   19  145   14   24 1289    5  153  153  273   12  970    2 
   O    P    Q    R    S    T    X    Z 
 129  386   26   11  291   79   46  112 
```
I need a data dictionary for this, but if same as MN, we should exclude L,M,R,S vegtypes where there is only one tree. Code currently does this. 

1613 no MI 1-tree points. About 1/4 of these have a 'notes' value, but only a small number indicate water, so not filtering based on this.

**Comment by paciorek** [comment]
Here is the data dictionary for WI (from Charlie).
[Wisconsin Metadata vegtype.docx](https://github.com/PalEON-Project/PLS_products/files/3132340/Wisconsin.Metadata.vegtype.docx)

**Comment by paciorek** [comment]
@jpeters7 just want to get your input once more on the 'wet' points. In MN I see about 1000 points marked as "wet prairie" and in WI I see about 500 points marked as "wet prairie". We are currently keeping all these points. 

In IL/IN I am currently excluding all points where tree1 is marked as 'water' or 'wet'. I'm concerned that the 'wet' points that I throw out might be similar to the 'wet prairie' in MN/WI, which I am currently keeping. 

Any thoughts in terms of how to be consistent?

**Comment by jpeters7** [comment]
@paciorek do the MN and WI "wet prairie" points have trees?  If so, then use the trees.  If not, then I think that those points are similar to what we have in IL/IN and would remove as we do in those states.

**Comment by paciorek** [comment]
Hmm, yeah, this is tricky. Let's consult with Charlie (I'll email as we should probably have a call to discuss a few things). We may also want to see what Simon and David have to say. I am worried that they would not have excluded such points in the past.

A few more notes:

In MN, 992 of 1004 vegtype Z points have no trees. 
In WI, 128 have 0 trees, 112 have 1 tree, 288 have two trees. 
So in WI, wet prairie does not mean too wet to have trees. 

I had been inclined to keep all these points as I am thinking they may not generally be standing water, but we are of course worried about consistency with IL/IN.

In Wisconsin 719 of 765 vegtype code 7 (low land / low wet area) have two trees, so it seems like we should just keep all vegtype 7 points as they are mostly treed.

**Comment by paciorek** [comment]
We discussed at 2019-05-13 call. Decided that wet prairie in MN/WI is terrestrial and should be included.

For consistency we decided that 'wet' points in IN/IL should be included but we should continue to exclude 'water' points.

In IN/IL:
water = standing water
wet = ephemeral water - surveyors provide some indication water is ephemeral

**Comment by paciorek** [comment]
Final note: there are 23 IN, 9 Detroit, and 37 IL points that are "wet" that we are now including. All have no trees.

**Comment by paciorek** [comment]
@jpeters7 Given our new treatment of wet, can you have the level0 to 3a conversion convert wet/Wet to "No tree"?
