### ISSUE TITLE
"Missing" (dead) trees in clumps in WI

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#37]
There are three large-ish areas in WI that are SW of Green Bay that have all of the points having "Missing" for tree 1 and no info for any other trees (see the blue areas in the attachment).

Perhaps large disturbances. I'm throwing these points out but would be good to check in with Simon and Charlie to make sure this is not something unexpected.
![wi_missing](https://user-images.githubusercontent.com/2501598/38890073-34bf99d4-4235-11e8-8810-a3f18029f7d9.png)

**Comment by SimonGoring** [comment]
The continuous blocks of blue near Green Bay were part of the Menominee lands and were not surveyed.

**Comment by paciorek** [comment]
Ah.  Is there anything in the dataset that would distinguish those points from the scattered other blue points (in WI as well as in MN and MI) where there were other reasons for having no data at a point?

**Comment by paciorek** [comment]
These points are being removed.
