### ISSUE TITLE
how to handle trees with diam < 8 inches

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#39]
My current inclination is to remove those trees and then find the 2 nearest trees from amongst trees above the veil line.

This is likely to induce a large number of 0-tree and 1-tree points that had small trees but zero or one larger tree. 

In Simon's stem density calculation he sets the density at a point to NA when there are not two trees of sufficient size. So that would then induce an NA for biomass. 

So that would be a possibly big difference in the processing and we should discuss.

**Comment by paciorek** [comment]
However, note that most of the small trees have diameters of 3-7 inches, so it's unclear if surveyors looked for bigger trees and didn't find them or were 'lazy'. 

In ~92000 of the ~151000 such points, the diameter of one of the trees was >= 8 inches. So perhaps this suggests that the surveyors often just couldn't find a big tree.

The small trees tend to be over-represented in the 2nd-nearest tree compared to first-nearest.

**Comment by paciorek** [comment]
Correction: while Simon's code allows for setting diameters < 8 to NA and therefore NA for density it looks like he didn't use this option, and his paper indicates that density was calculated from all trees and then a correction factor was applied. However, this leaves open the question of whether to set biomass for the small trees to 0 or to calculate it, or to remove such points. If we think the surveyors were just ignoring bigger trees, that would argue for removing such points. If bigger trees were hard to find at such points, then using the smaller biomass or zero for such points would probably be appropriate.

**Comment by paciorek** [comment]
Perhaps we should not apply the density correction factor but compute a density at each point that is implicitly conditional on the veil line used by the surveyor and then calculate biomass based on the two nearest points. For cases where the surveyors included trees <8, the resulting biomass is not defined quite the same as what we want (which is biomass of trees >= 8) but since the small trees have low biomass, perhaps it is close enough and better than disregarding such points.

**Comment by paciorek** [comment]
Another idea is to use the corrected density (i.e., density for >=8 inch trees) and then only use trees >= 8 in the biomass calc. This treats the size of the 'missing' trees as unknown. We might also use the third and fourth trees if they are available and >= 8.

There is a concern here that we end up with a lot of missing data in the low biomass areas. But I think that is not a cause of bias,

**Comment by Kah5** [comment]
According to Charlie, the "Phi" correction factor in the morisita estimator takes the density estimated for all trees and corrects it to a value that is the density of all trees >8 inches. Because of this, it seems like we would also want to have biomass of only trees >8 inches.

**Comment by paciorek** [comment]
Yep, that is how I see it as I've been musing about it. My current thought is:

- Case A: 2 trees, both >= 8: we can proceed as is
- Case B: 1 tree >= 8: we can proceed with the estimated biomass for the represented taxon and 0 for the other taxa since a 1-tree point means there was only one taxon nearby
- Case C: 1 tree < 8: I think we may want to impute a 0 for biomass for the represented taxon, as well as 0 for the others, since density is going to be low and we know biomass is low for small trees. If diameter is missing, we might still impute a 0, but perhaps treat as missing.
- Case D: 2 trees, both < 8: we can estimate density, but biomass is missing
- Case E: 2 trees, 1 >= 8, 1 < 8: for the taxon of the big tree, we can estimate biomass. We can also if we wish estimate total biomass based just on that one tree, though the estimate is higher variance than at standard 2-tree points. For the taxa not represented, we have NA as the biomass because we don't know the size or taxa of the tree >= 8 that the surveyor would have found if they had been more "diligent".

**Comment by paciorek** [comment]
Summary for 4/26/18 call:

See Chris' proposal in comment just above.

**Comment by paciorek** [comment]
8 became the veil line later in time. Varies in time and space. 

Charlie: Estimate density and biomass w/o veil line accounting. Interaction of dens and size tends to correct. 

For stem density product  - do calculation without correction. Omit phi.
