### ISSUE TITLE
discuss big trees

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#40]
Simon was entirely removing points with trees > 100 in diameter. Seems reasonable given these may well be typos. There are a few hundred trees with 50-100 in diameter, and many such trees could be real.

One caution is our allometries have little data bigger than 70-100 cm = 28-40 inches, so there will be lots of variability in biomass for the big trees.

**Comment by Kah5** [comment]
Removing trees >100 inches seems arbitrary to me. These would be large trees, and some are likely typos, but it is possible that some are real. If there is a sound reason to set the cut off at 100 then it would be good to do. I don't think we are currently removing these for IN/IL

**Comment by SimonGoring** [comment]
We looked through the distribution of diameters and needed to set a threshold.  We checked with DMlad when we set this threshold. It’s posible to validate by checking both the set of taxa/diameters found in proximity to the trees with these large diameters, but dbh > 100” is a tree that is over 8ft in diam.  One, it’s hard to differentiate between things that are genuinely in error and trees that are gigantic, two, because biomass is cubic it blows up the volume for any single cell, so I suspect that played into it as well.

**Comment by paciorek** [comment]
Summary for 4/26/18 call:

Need to decide if 100 in is a good cutoff and whether to omit or truncate the very large diameters.

**Comment by paciorek** [comment]
Where are the big trees? And dist of species? What about dist for 80-100 inch diameter.

Charlie thinks 100 is a good choice. 

Simon probably talked to David Mlad.

could be willows.

**Comment by paciorek** [comment]
I looked at trees with diam > 72 inches.

Here are the counts, first for > 72 and next for >= 100
```
> data.frame(table(big$L3Mx[big$L3Mx>=100]))
                  Var1 Freq
1                  Ash   20
2         Bald cypress    1
3             Basswood    9
4                Beech   21
5                Birch    7
6  Black gum/sweet gum    1
7        Cedar/juniper    4
8                  Elm   26
9                  Fir    2
10             Hemlock   11
11             Hickory   16
12            Ironwood    1
13               Maple   19
14                 Oak   77
15      Other hardwood    1
16                Pine   17
17              Poplar    5
18              Spruce    8
19            Sycamore    4
20            Tamarack    7
21              Walnut    2
22              Willow    1
> data.frame(table(big$L3Mx[big$diamMx>=100]))
                  Var1 Freq
1                Beech    5
2                Birch    3
3  Black gum/sweet gum    1
4        Cedar/juniper    2
5                  Elm    4
6                  Fir    1
7              Hemlock    3
8                Maple    5
9                  Oak    6
10                Pine    5
11              Spruce    5
12            Tamarack    4
```
Note that oaks are generally mix of white and black and maples are either ambiguous or sugar (couple of red). 

Attached are histogram of sizes, plus a map. Sorry about the color scheme - it's a bit hard to distinguish 
[big_trees_hist.pdf](https://github.com/PalEON-Project/PLS_products/files/1956151/big_trees_hist.pdf)
[big_trees_map.pdf](https://github.com/PalEON-Project/PLS_products/files/1956152/big_trees_map.pdf)



Attached is hi

**Comment by paciorek** [comment]
Charlie says "As a quick fix to the diameter errors in southeast Michigan, I have stripped all corners with an azimuth bearing of 0 (which should be the displaced diameter) and recalculated the correction factors.  They are very close, but  lower biomass will result since many (~528) large diameters have been removed. I attach the corrected southern Michigan corrections. If needed I could reconstitute the whole of southern Michigan, but my format is slightly different from Jody's.  Note differences are only for East of the Meridian and it is straight forward to filter out all the 0 az1 & az2 bearing corners.  Chris's question on the source of the error is unclear, but it could be either in the production of the mylars or their transcription.  In the meantime this fix should bypass much of the problem. "

Chris doesn't see any cases in SE MI where both az1 and az2 are 0 nor cases where az1_360 and az2_360 are 0 so needs to get more info from Charlie on the exact form of the criteria to use for exclusion.

**Comment by paciorek** [comment]
Chris:

Also, Charlie, here are the diameters of the big trees >= 100 (you had
asked for this, but not sure if you still wanted to see as it seems
you looked more in depth at the data in the intervening time).

1018  481  412  323  317  297  277  215  212  210  202  169  167  161  156
154  147  147  146  140  133  127  125  121  120  120  120  120  118  118
118  118  118  114  114  114  114  113  113  112  112  112  111  109  107
104  102  100

And this is probably not relevant here are the diameters of trees >=
100 that are _not_ amongst the closest 2 trees:
1212  436  247  195  147  146  114  105  101

Charlie: 

Except for the 120s they are not multiples of 12s and the odd numbers especially double 1s indicates they are all bogus diameters.  I suspect detailed comparison with the mylars might resolve some of these, but definitely eliminate all corners with these data.

**Comment by paciorek** [comment]
az = 0 is for original bearing 0-90 value which also could include 9999 or NA.  Note cardinal directions should not include any bearing, but can be recorded as 0 or converted to 0 using "notes". Thus you must also check alphanumeric bearings and "notes" to make sure they are not legitimate az0s! Eliminating all az 0 corners is a conservative quick approach that should eventually be corrected by comparison with original mylars. To save time I will try to filter all E of the meridian in southern Michigan and filter table for illegitimate az 0s.

**Comment by paciorek** [comment]
Charlie:

The procedure was to remove all  corners with trees > 100". Then identify all sp1 trees with 0 bearing, but not those with comments field indicating arrows or specific cardinal directions. Remove these corners. Identify additional sp2 trees with 0 bearing, but not as above. Remove these corners. Correct sp3 and sp4 trees with 0 bearing to complete the complementary quadrant with a 45 bearing. This should get close, but I suspect that other errors are embedded and someone should do a good QA on all the southern Michigan data.

**Comment by paciorek** [comment]
Further clarification by email:

[from Charlie] Chris,

For the record.  The East of the Meridian -- Southern Michigan file was initially cleaned up for azimuths with incongruous values.  First, if azimuth is missing -- 9999 or comment "missing", but not 0-- and the quadrant is known, a 45 bearing is inserted which preserves the quadrant and "averages" the bearing.  If the bearing is  >90, --usually double hits or overlapping  fields-- the obvious typographical errors were corrected otherwise the corner is discarded. Second, trees >100" had numerals redistributed over clearly empty fields or the corner discarded. Third, all 0 bearings were scanned for notes in the comment field to assign cardinal directions, that is true 0 to 360 azimuths.  Fourth --most importantly due to numerous large diameters up to 89" in Detroit region-- any tree with a remaining 0 bearing was assumed to have corrupted diameter and azimuth fields and the corner discarded. This is very conservative as bearing errors do not affect density, and diameter errors were eliminated for the least reason. Additionally, only about 3% of the corners were discarded.  The only better procedure I see would be to QA the entire southern Michigan database. 

[from Jody] I did as Charlie did {removing points with trees > 100"}  AND {removing points points with 0 azimuths}.
Charlie - in the East of the Meridian --Southern Michigan file, did you change any diams, az or distances to redistribute the numerals?  Or did you just remove the trees >100 and the points with 0 azimuths?
Right now I'm just using the FIDs to choose the entries from our southernMI_projected_v1.4 file. But if you made changes to redistribute numerals in your East of the Meridian file in this last round of QA, then I should use the data from your file.
I'm happy to update the file to southernMI_projected_v1.5 to put on the wiki or provide this list of FIDs. Whatever you prefer Chris.

[from Charlie] Jody,

Any redistribution was done in the original screening of all southern Michigan in January, so the only changes relevant to East of the Meridian are the recent stripping of >100" and odd azimuth stripping of corners. Thus go with your updated EofM changes which should be the CVC clean original with ~435 corners removed. The problem avoided is the apparently large number of large diameter trees near Detroit which skewed the biomass. This is a good defensible approximation. 

[conclusion] Jody to create file with FIDs to exclude. Exclusion will then be done in 1_clean...R

**Comment by jpeters7** [comment]
I added file "southernMI_FID_removal.csv" to the wiki. There are 429 FID values from corners east of the meridian in southern Michigan that should be removed from the density analysis.

**Comment by paciorek** [comment]
Charlie:

The procedure was to remove all  corners with trees > 100". Then identify all sp1 trees with 0 bearing, but not those with comments field indicating arrows or specific cardinal directions. Remove these corners. Identify additional sp2 trees with 0 bearing, but not as above. Remove these corners. Correct sp3 and sp4 trees with 0 bearing to complete the complementary quadrant with a 45 bearing. This should get close, but I suspect that other errors are embedded and someone should do a good QA on all the southern Michigan data.

**Comment by paciorek** [comment]
A note that the result of the exclusion of the FIDs is that we remove 5 square-ish blocks from far southeastern MI. I.e., the removals are not scattered but concentrated. See attachment: left is before the FID removal and right is after.
[southern_MI_removals.pdf](https://github.com/PalEON-Project/PLS_products/files/2010617/southern_MI_removals.pdf)

**Comment by paciorek** [comment]
Also presumably related to the SE MI issues above, I note that some 200-odd corners in far southeastern MI have either first or second diameter of 0  despite seemingly legitimate taxon and distance.

In figure red points are the cases where first tree has 0 diameter. In almost all of the corners in the red blocks in the SE the second tree also has diameter 0. 
[southern_michigan_0_diam.pdf](https://github.com/PalEON-Project/PLS_products/files/2010665/southern_michigan_0_diam.pdf)

**Comment by paciorek** [comment]
One other note, there are still some large (>50") trees in SE MI that cause a hotspot in biomass estimates. The 8-10 such trees are all in FIDs whose numerical values are similar to the FIDs that we are excluding: 7808, 8397, 8399, 13348 ,13364, 13671, 16540

**Comment by paciorek** [comment]
Charlie says:
```I received the mylar database in good order and have unzipped and analyzed the recorded data.  Evidently the diameters of trees in Monroe County and adjacent tiers of townships in Lewanee, Washtenaw, and Wayne Cos.were not included on the mylars.  Specifically the general recording of 3d numbers (diameter, direction, distance) for most of Michigan is not followed in the southeast corner where 2d (direction & distance) only  are recorded on the mylars. The diameter fields are missing and the data were transposed among the bearing and distance fields.  Thus the diameters are ALL bogus and the distances garbled.  This means that without a complete redo of the mylars from the original field data we have no way of calculating basal area or biomass from the available data in approximately 50 townships in southeastern Michigan.   I am currently producing a shape file containing all the earlier adjustments of the southern Michigan data including the correct bearing and distances from the southeast corner (Note that density can still be calculated).  This can be used to get a complete density coverage, but we will not have basal area or biomass estimates for this region.  

My perusal shows the mylar missing diameters in 25 townships in Monroe and Lenawee Cos.  Specifically they are T8S R3E to 8E, T6S R 3E to 8E, T6S R 4E to 9E, T5S R5E to 10E, & 10 corners inT4S R5E in southern Washtenaw Co..   If these could be recorded anew, perhaps including whether section or quarter corner and the direction of travel it would be flesh out comprehensive coverage for Michigan. I checked in the digital file from Seeking Michigan and the interior notes are from vols. 0020 to 0065 of survey notes contain all data are easily readable.
```

@jpeters7 please post a file on the Wiki that will allow me to exclude these points from biomass calcs. Not sure exactly what info/format I need, but I think you'll have a good sense of this.

**Comment by jpeters7** [comment]
@paciorek - I'm heading out for a meeting in Boston through the rest of this week. If I don't get to this while I'm away, I'll get it to you early next week!

**Comment by paciorek** [comment]
Charlie will do spot checks of > 100 diameter trees in MI.

**Comment by paciorek** [comment]
Charlie has checked (and as necessary fixed) all trees > 50 inches diameter in MI.
