### ISSUE TITLE
clear up 2nQ correctin

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#42]
This from Charlie:

Going over the density map and my code, I realized that I am unsure how the 2nQ (all four tree corners in Simon's code) has been invoked in these maps.  Originally I think there was a constant (~0.8573 or 0.856313) embedded in Simon's code which "converted" the Morisita raw density based on opposite halves sampling to two nearest sampling (2nQ).  Several years ago I realized that this was the correction for the Cottam estimator, but the Morisita estimator required a 0.82 conversion.  This was changed in my code, but I have never checked Simon's.  Directly related is the Kappa "correction"  for 2nQ listed in the after-the-fact multipliers listed in Jody's yesterday posting to the wiki.  The 2nQ conversion constant listed here is the old one and should be changed to the correct 0.82.  I do not know if this constant is ever used as the correction might have been made internally or possibly the factor is duplicated.   Thus we should immediately check if and  where the 2nQ conversion is invoked and make sure the constant is 0.82 throughout.  Sorry about any confusion, but this makes a 5% difference in density  in up to one-third of  corners and must be confirmed or corrected immediately.

**Comment by paciorek** [comment]
In the current version of the code, we are not doing any correction using numbers directly embedded in the code. All the correction values come from the corrections factors file. 

That said, as far as I can  tell, in the last version of Simon's code, he never used the 'point'  column (which distinguished 'P' from '2nQ') to determine which line to use from the corrections file. 
(See the lines around line 118 of load_data_v0.2.R.)
Therefore in my current version of the code I am only using the 'P' rows from the corrections file and not the '2nQ' row.

So I believe we are never using the 2nQ correction (neither the incorrect 0.8573/0.8563 values that are in the file nor the correct 0.82 value).

**Comment by paciorek** [comment]
Charlie says:

It is reassuring that the 2nQ correction is not yet invoked.  It is, however, important to note that ALL original four-tree corners have been reduced to two-tree points in Simon's analysis and have to be flagged since they are not treated as normal P (=pair) correction factors.  They must be multiplied by the conversion factor (0.82) and use the four-tree azimuth and diameter corrections (found in 2nQ rows) unique to four-tree sampling! We'll discuss and resolve this Thursday

**Comment by paciorek** [comment]
My question is why all of the points from so MI, IN, IL are not also thought of as originally being four tree corners.

**Comment by paciorek** [comment]
'P' for pair - original 2 tree corners
'2nQ' - all 4  tree corners

Has to be flagged from beginning.

soMI/IL/IN mostly P. If see 3/4 trees then it's 2nQ.  If it's 2 then 'P'. 

If see tree at 0 dist, then that is the first tree. 

Rare to find only 2 trees if they looked for 4.

Need need new correction factors for 2nQ for soMI/IL/IN.

4 tree tend to be section corners. 

For UMW, looks like Simon did not use P/2nQ. Perhaps redundant. Charlie: there is a mixture.

Simon: sum non-water/non-tree and decide if >3/4 then 2nQ.

**Comment by paciorek** [comment]
If see diam/dist but not taxa, then didn't count as tree in UMW. 

Charlie thinks it does indicate a tree was there.  So do count as tree.

If we see some water, there can't be a tree. Some of circle is censored. It's not 2nQ. 

E.g., with 2 water points, treat as 'P' and just use density.


There are 2sh corner corrections. (Factor of two).

**Comment by jpeters7** [comment]
I have added the IL and IN correction factors for the 2nQ trees to the "charlie_corrections_full_midwest_v1.0.csv". It is on the wiki.

**Comment by paciorek** [comment]
Added Pair vs 2nQ based on counting trees (omitting NA, No tree, Water). 

Also I looked for cases where taxon was missing but existing diam/dist. Very few of these:
3 in MN amongst first tree have diameter
no clear missing taxon info in WI
2 in noMI amongst first tree have diameter
Will ignore these cases.
