### ISSUE TITLE
northern MI missing year

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#45]
there are 47 points with survyr=2. See attached (red points).

It looks like we are assigning one correction factor to whole of UP, so we should just use that for these points with survyr=2. 

[no_mich_year_equals_2.pdf](https://github.com/PalEON-Project/PLS_products/files/1975008/no_mich_year_equals_2.pdf)

**Comment by paciorek** [comment]
Jody is adding UP vs LP to northern MI file; that will obviate this issue.

**Comment by jpeters7** [comment]
As I was going through the northern MI file to label the UP vs LP point, I found out that the points are already separated into UP and LP via the FID values.  We can use the code below to label the UP vs LP points. I wasn't sure the best place to add the code.

up.mi <- mi[(mi$fid %in% 0:49644),]
lp.mi <- mi[(mi$fid %in% 49665:96141),]

**Comment by paciorek** [comment]
@jpeters7 I don't see an FID field in the no MI CSV.

**Comment by jpeters7** [comment]
@paciorek that's really weird.  I just downloaded the zipped file from the wiki and it is on that one (see image below). The northern MI file name is correct in the config file as well. And in the 1_clean R file, I don't see that the FID field gets removed.  So I'm not sure where the mismatch is coming from.

![image](https://user-images.githubusercontent.com/6137819/39827991-84d92602-5387-11e8-9907-ed521a236ce3.png)

**Comment by paciorek** [comment]
Must have been a problem on my end with incorrect file. Redownloaded and things look fine.
