### ISSUE TITLE
use UMW taxa translations for Schoolcraft and Isle Royale

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#47]
Given Schoolcraft and IR data will be in so MI file, should I set up the code such that we use the UMW translations rather than the so MI translations?

**Comment by paciorek** [comment]
Jody will provide these data as a northern MI supplement file; Chris to update code based on the new data file -- load in southern MI and the northern MI supplement, then do the taxa translation separately and combine for further processing.

**Comment by jpeters7** [comment]
the northernmi_pls_projected_supplement_v1.0.csv with the Isle Royale and Schoolcraft corners are now on the wiki and the file name is updated on the config file.
