### ISSUE TITLE
extra columns in corrections file v1.1

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#48]
@jpeters7 there are about 20 empty columns in the v1.1 of cogbill_density_corrections...

I can omit them, but just want to make sure they don't indicate some other problem. And for cleanliness would be good to not have them.

**Comment by jpeters7** [comment]
Those were just left over from the file that Charlie sent. They were blank. I have removed them and re-uploaded the file to the wiki.
