### ISSUE TITLE
lower density of points in southern MI

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#49]
@jpeters7 I noticed that the southern MI have a lower density of points at which we have data, which I think we probably knew. However, I also noticed that the density seems to correlate with whether the area was open or forested (there seem to be more points in areas that were heavily oak in the composition product and therefore probably savanna/prairie. See attached plots of (x,y) coordinates of all points 
[mi_points.pdf](https://github.com/PalEON-Project/PLS_products/files/2005523/mi_points.pdf)

The right panel is a blow-up of one area that highlights the difference between the northern LP and southern LP, but also shows higher density in a blob within southern LP that was heavy in oak based on the composition product.

**Comment by jpeters7** [comment]
When I was going through the southern MI data, I had also wondered why some areas of southern MI had section corners AND 1/4 section corner data while others only had section corners.  But I never followed up on it...  That is interesting that it seems to correspond with open/forested areas. @SimonGoring can you add anything here from your experience with the mylar data?

**Comment by paciorek** [comment]
Additional comments from emails with charlie:

Charlie: 
There seems to be some township differences in the inclusion of 1/4 corners which is attributable to surveyor difference.  The stark difference between the so./no. LP boundary is also puzzling.  We must look at the mylars to see if there are clues.

Charlie:
It seems backwards, as I would expect thicker woods would demand more monuments.  Equally problematic is the general lack of quarter-section corners. Is the transcription involved?  Were corners surveyed, but not recorded?, Perhaps when in savanna they were more important? I will check if the actual density differed among corner types.   I will also delve into the deep literature on southern Michigan surveys and see if surveyor methodology or forest type was noticed in other studies. Again the mylars should tell the tale.

Charlie:
Quick perusal of Battle Creek region (south central so. Michigan in oak region) shows section corners with base 170-230 t/ha and 17.0-24.0 m^2/ha with quarter section corners of 45-60 t/ha and 3.2-6.6 m^2/ha.  This is dramatic and confirms your observation that the quarter section corners (1318 corners) were in savanna and section corners (3399 corners) in forest.  Still does not answer why and a caution that were do not let a surveyor bias skew the density data (where available quarter section are twice as numerous as section).

Chris: 
Since we are doing analysis at the grid cell level, I think that will potentially fix a lot of the bias that might creep in. If the surveyor behavior is consistent within each grid cell then we just end up with a larger sample size in the grid cells that were more open. Of course to the extent surveyor behavior changed as they went in and out of open areas, then we bias density and biomass low within a grid cell because of the extra corners that are included are preferentially low density.

We can presumably exclude quarter section corners from southern MI, but let's see what your further investigations reveal.

**Comment by paciorek** [comment]
checking in again with Charlie and Jody by email.

**Comment by paciorek** [comment]
Charlie: 
At least in theory the surveyors should choose 1/4 sections in exactly the same way as section corners.  The major difference is in the choice of quadrants/halves in which witness trees occur and minor differences in marking of the trees. There are differences in density calculated from the two sets, but much of this is due to sampling design including the incorporation of smaller diameters. The correction factors should accommodate much of this difference, and I encourage a sensitivity analysis to test the influence of factors (such as savanna, state, diameters, sampling design such as one-sided exterior corners, etc.) causing any differences between section and quarter-section corners. Any southern Michigan analysis should use the Detroit data only.  Also checking the proportion of 1/4 section corners in savanna areas especially the occurrence of single trees would be informative.  Kelly should have a perspective on these density calculations in savanna areas.  Thanks for checking on these loose ends and our products will be solid with the mutual understanding.

**Comment by paciorek** [comment]
I'm leaning towards excluding 1/4 section points in southern Michigan given the plots below that indicate that quarter section corner sampling seems to have primarily been done in low-density areas. If it were such that in a given large-ish spatial area, that if there were savanna in general then 1/4 section samples were taken (e.g. in south-central Michigan), then in would just mean we would have higher density data, but unbiasedness in some areas. But the plots below indicate that it's possible that the decision to sample 1/4 section corners was done based on the local density (see, e.g., southwestern Michigan) then we would induce bias.

Corners sampled:
[soMI_corner_info.pdf](https://github.com/PalEON-Project/PLS_products/files/3050876/soMI_corner_info.pdf)

Density only from section corners:
[soMI_section_density.pdf](https://github.com/PalEON-Project/PLS_products/files/3050878/soMI_section_density.pdf)

Density only from quarter-section corners:
[soMI_quarter_density.pdf](https://github.com/PalEON-Project/PLS_products/files/3050880/soMI_quarter_density.pdf)

**Comment by paciorek** [comment]
Note that for the Detroit data that has been systematically re-entered by ND, we will presumably include quarter-section points.

**Comment by jpeters7** [comment]
For what it is worth, I went back and looked at 5 townships in southern Michigan (2N1W, 8S3W, 5N14W, 7N14E, 6N14E - I'm happy to scan more if needed). They all have notes for the 1/4 section included.  From looking at the notes for the Detroit data as well as notes when doing the QA/QC with Charlie for the rest of Michigan, I am confident that the original survey notes include notes/trees for the 1/4 section corners.  I'm just not sure the mylar transcriptions did not include the 1/4 section corners. The pattern of 1/4 section locations in general, do seem to line up with the oak savanna areas. However, there is that square group of townships in Allegan county on the west side of the state that seems more systematic and not necessarily related to density.

**Comment by paciorek** [comment]
I'm excluding the southern Michigan quarter section points.
