### ISSUE TITLE
update level3a to level3s

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#50]
@jpeters7 for some reason in current (v0.3) of the 3a->3s conversion we have no level3s corresponding to bald cypress, but as you pointed out in email, probably makes sense to lump with cedar/juniper.

What do you think about changing the bald cypress line to:
Bald cypress,Cedar/juniper,no,no
and updating to v0.4 of 3a->3s?

(Formerly the last 2 columns were 'yes' because we weren't lumping with another taxon, but I didn't want to model a rare taxon like bald cypress)

**Comment by jpeters7** [comment]
Sounds good. I updated to v0.4 and uploaded to the wiki.
