### ISSUE TITLE
biomass hotspots (mostly Michigan, also check high Indiana biomass)

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#53]
We have a hotspot of biomass up to ~600 Mg/ha in the UP (see right panel of attached); from cells 15481,15482, 15483, caused by a large number of trees 2-4 feet diameter. This seems legit based on the data in the northern Michigan CSV file but might be worth more discussion.

[fits.pdf](https://github.com/PalEON-Project/PLS_products/files/2202910/fits.pdf)

@jpeters7 remind me what the source of the northern MI data is and whether we have any ability to go back to the raw data in some fashion?

**Comment by jpeters7** [comment]
@SimonGoring can we go back to the raw data for the Upper Peninsula of Michigan? The biomass hotspot is mainly in Dickinson County, which I don't believe was part of the additional UP data that we got with the southern Michigan data. I believe these UP data came from Ed. Did you guys get it as mylars or had Ed already transcribed it?

**Comment by paciorek** [comment]
Here are the x,y coords of the 3 cells and attached is a CSV (notwithstanding the '.txt' extension) with the 67 rows of data from the raw northern MI file that are the problematic area:
```
       x       y  cell
   <dbl>   <dbl> <int>
1 637000 1078000 15481
2 645000 1078000 15482
3 653000 1078000 15483
```
[noMI_big_sites.txt](https://github.com/PalEON-Project/PLS_products/files/2266932/noMI_big_sites.txt)

**Comment by paciorek** [comment]
Charlie: After perusal the biomass hot spot in the UP (Dickinson Co) is mostly attributed to several corners in T44N R29 & 30 W where the diameters and distances are transposed  The mylars are clear that most diameters > 60" are bogus and the actual diameters are recorded in the distance (or bearing in several cases) column.  See ID 43057 with 4 trees with 277", 436", 146" and 195" diameters which actually are 14", 14", 18", and 6" which alone dominates the biomass spot in the UP. Similarly the hot spots around Saginaw -southern Michigan are due to abnormally large tree diameters which are apparently transcription errors. The only solutions are to go through each of the large diameters (say >60") and either de-transpose or find the same corner on the mylars to be assured that the transposition is correct or the delete the corners as corrupt. The UP data errors are relatively limited and easily corrected and the southern Michigan errors will be mostly corrected by the  Monroe/Lenawee  redo.  However many scattered southern Michigan still remain and the biomass will not be accurately estimated if these points are retained. For perspective the mylars are indexed by quadrangle without much internal reference to township, but with a little work and use of the state.dnr spatial area county maps the general location can be alined. This could be speeded up if the twp/Range and point # for each aberrant diameter (>60") is compiled and the mylar perusal made more efficient.  

Jody: I have corrected the dbh/distances for ID 43057 in the northernmi_pls file - currently saved as v1.2 on my computer, but not yet uploaded to the wiki.  
Charlie - if I went through the northern and southern Michigan files and compiled a list of all trees >60" with their Twp/Range and point # - would you have time to look at the mylars?  Or if you don't have time, could we set up a zoom call where you could share your screen and walk me through how to do it?
Chris - today I will get you the list of Monroe/Lenawee corners to exclude until our undergrads are able to enter the data from the original PLS notes this fall.
I hope that Charlie and I can get the additional trees with diameters >60" worked out in the next couple of weeks and then I can put the new northern and southern MI versions on the wiki, but if you want the northernmi_pls version 1.2 now, I can upload that now.

**Comment by paciorek** [comment]
After Jody/Charlie/Chris phone call, here is plan for investigating the biomass hotspots:

- UP (Dickinson) - Charlie will proof/redigitize after Jody points him to more detailed info on twp/rg
- north of Saginaw Bay: decimal distances - mistake chains for links - Chris to generally look for decimals: decimal of 1.1 means 1.1 chains=110 links (link is ~7inches)
- SW of Saginaw Bay: Chris to identify corners/area
- SE Michigan: mylars are incomplete (no diameter, faulty diameters generated); only 25 so Jody says students can do quickly at beginning of semester; in interim, Jody will add the Detroit area FIDs to southern_michigan_fid_removal.csv. That removal file also has additional 103 scattered southern MI flagged to remove (diameters >= 100 and azimuth of 0 for any of the four trees); Charlie says to go down to max diam of 72, which Jody will do
- western MI: identify corners/area
- IN: look at biggest red blob and point Jody to corners/area

**Comment by paciorek** [comment]
Charlie: A first scan of the Saginaw hot spot shows that it is a true transcription of the mylars.  In addition the mean, median, and quadratic mean diameters are only marginally higher than from nearby regions. Digging down in the data and comparison with the original field notes there are subtle errors : 25861 wwal 32 16 1 is really 32 north 16;  15049 maple 18 40 1 is really maple 18 40 1-1/2 lks; 25865 (from yesterday SM 9 54 1  WP  40 46  1 is really WP 40 46 missing;  376  BCH 5 11 1 is really BCH 5  11  1-1/2;  12524 elm  9  30  1  is really elm  9  30  missing; 3308  wo  10 78  0 is apparently wo  10  78  06;  3302  ash  12  4  0  is really ash 12  4   4;  and there are probably trouble with almost all corners with distances of 0 or 1. The litany of errors are handwriting, insertion of 1 when 1-1/2 is in the notes, superfluous entry of 0 or 1 at whim, and standard transcription errors.   Significantly the first three errors (25861, 15049, 25865) alone reduce the predicted basal area from 61.3 m^2/ha to 44.3 m^2/ha over 371 corners.  If the other 1's and 0s (24482,  3273, for two tree and 12502, 24602, for four tree corners) are eliminated the basal area is reduced to 44.1 m^2/ha.  A similar 1/3 reduction of the biomass should follow.  This should reduce the Saginaw hot spot to the high side of the region in accord with the basal area and relatively numerous large trees. There is a choice for any rectifications, but the first three corners are the culprit and correcting the others  or getting rid of all 0s and 1s is justifiable.  An efficient screening is to look at corners with a very small sum of distances squared (e.g.0^2 + <3^2, with 25865 sum sq = 2). The problem with Saginaw is not the size of trees, but the inclusion of very short distances.   Also this shows that a few corners especially if very close to the post or even slightly inaccurate causes the whole density with basal area and biomass to blow up. Of course the situation can be real if a large tree is within 1 to 2 links, but that is physically problematic. This also applies to corner trees (0 distance-  note that none of the above are true corner trees but transcription errors onto the mylars)   On to the other hot spots tomorrow.

Chris: I didn't follow all of what you said, because when I look at the 179 rows in the saginaw hotspot CSV, there are only a few rows with dist1 or dist2 less than 2, and when I remove them, the average biomass across all remaining corners doesn't change that much.

**Comment by paciorek** [comment]
Charlie: I have done a detailed look of the five biomass "hot spots" in Michigan and find that the Detroit, Dickinson Co., and Iosco Co. (north of Saginaw) have obvious errors (mylar transcriptions without diameters (Detroit); of distance and diameter transpositions on mylars (Dickinson & Detroit to a degree); distances recorded in decimals or chains (2 twps in Iosco); and a few scattered transcription errors from field notes (particularly in Saginaw).  Other than that the database appears clean and produces HIGH basal area values for Saginaw and Ottawa Co. (western hot spot).  I am puzzled about the degree of deviation from expected values, but that is purpose of our research to determine the actual patterns. The only other analysis I can see is to make sure the calculations and correction factors for Saginaw have be correctly applied (it would be helpful to get a numerical map of Saginaw biomass) .  I am eager to pursue further analyses, but would be open to a phone conference before continuing.
