### ISSUE TITLE
a few taxa conversion issues in southern MI

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#57]
Jody, when you get to the point of looking at missing taxa codes for southern MI, the four cases I noticed are these. I think every other L1 taxon code in the v1.5 southern MI file matches a L3 code.

The cases are:
  - first one - "0" as the taxon for tree 4
 - second one - unknown taxon:  "PS" 
 - third one - unknown taxon: "ke"
 - fourth one - unknown taxon: "spo"

```
    FID L1_tree1 diam1 q1 az1 az1_360 dist1 L1_tree2 diam2 q2 az2 az2_360 dist2
1 17389      bch    11  3  42     222     6      bch    16  4  27     333    28
2 22921       PS     8  4  30     330    28       PS     9  2  45     135    61
3  4125       ke    11  1  63      63    28     wash    11  4  63     297    25
4 25975      elm    20  0  66       0    44      spo    50  4  24     336    16
  L1_tree3 diam3 q3 az3 az3_360 dist3 L1_tree4 diam4 q4 az4 az4_360 dist4
1     <NA>     0  0   0       0     0        0     0  0   0       0     0
2     <NA>     0  0   0       0     0     <NA>     0  0   0       0     0
3     <NA>     0  0   0       0     0     <NA>     0  0   0       0     0
4     <NA>     0  0   0       0     0     <NA>     0  0   0       0     0
```

**Comment by jpeters7** [comment]
I have corrected the southernMI_v1.5 file. The 0 was removed. The "PS" was changed to "sp" so it matched the southern Michigan Level 0/1 to Level3a (northern Michigan conversion uses PS...), The ke and spo were corrected to wash. I will update the southern MI v1.5 file once I check that all the other issues are corrected.
