### ISSUE TITLE
rename detroit file in zip

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#70]
@jpeters7  can you make MI and D lowercase in 
southernMI_Detroit_projected_v1.0.csv 
southernMI_Detroit_projected__v1.0_README.txt

would be nice to keep it consistent with lower-case of other file names in various zips.

Also please remove the duplicated _ in the README file name.

**Comment by jpeters7** [comment]
Done! I left Detroit capitalized. Should that be lower-case?

**Comment by paciorek** [comment]
yes, please use 'detroit' since everything else in these various file names is lower case.

**Comment by jpeters7** [comment]
Done!
