### ISSUE TITLE
problems in v0.7 level0 to level3a conversion file

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#71]
@jpeters7 in the new conversion file there are no "No tree" entries for IL/IN/Detroit. We need them so the L1 to L3 conversion goes through. Do you know why they were lost?

Also in the IN conversion rows, I see this:
```
buttonwood,,,,Sycamore,,Indiana v1.8,
```
There is no entry for the L1 column so any NA in L1 for Indiana is getting converted to Sycamore in L3. Now we shouldn't have any NA in L1 and my code checks for this, but we do have one buttonwood, and regardless we'd want to fix this.

Also while you're at it, can you add rows for "no tree" (as well as "No tree" per the above) for IL/IN/Detroit? I think it's cleaner to have it in the conversion file than for me to convert from lower to upper case since I am not converting any other L1 values between lower and upper case.

**Comment by paciorek** [comment]
Also should we have a version number as part of "Southern MI_Detroit_ND" in the conversion file?

**Comment by jpeters7** [comment]
I updated my PLS Summary code and now have the No tree, No data, Water, and Wet conversions included in the updated level0 to level3a v0.8 conversion file.  v0.8 is now listed in the config file.
v0.8 also has the buttonwood issue resolved and Southern MI_Detroit_ND now is listed as v1.0.

**Comment by paciorek** [comment]
As far as I can tell, the v0.8 file on the Wiki is still missing the various No tree, No data, Water, Wet conversions for IL/IN/Detroit.

**Comment by jpeters7** [comment]
I must have saved the file incorrectly.  I have updated the v0.8 conversion file on the wiki now with all the corrected info fo No data, No tree,  Water, and Wet for IL/IN/Detroit. The Buttonwood issue has also been resolved. Changed the XA, XB, XC, XX to No data for
