### ISSUE TITLE
missing some Detroit points?

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#73]
@jpeters7 it looks like we are missing some points in the Detroit area? There seems to be an inward bulge with no points right around the city. Thoughts?

(Black are ND's new Detroit points. Red are the southern Michigan data.)

[detroit_points.pdf](https://github.com/PalEON-Project/PLS_products/files/3100487/detroit_points.pdf)

**Comment by jpeters7** [comment]
There is no data for this area.  I believe it was settled prior to the PLS surveys.  I'm sure Charlie knows the details about this, but you can see on our GIS map that we don't have townships/sections and there were no notes for this area that we could transcribe.
![Detroit Hole](https://user-images.githubusercontent.com/6137819/57164058-eedb2b00-6dc0-11e9-9073-96638615b01b.png)
