### ISSUE TITLE
'bearings' columns created but not used

### ISSUE THREAD

**Issue by paciorek** [PalEON-Project/PLS_products#8]
This code appears in 1_clean_merge_point_data.R, but 'bearings1' is never again used. Same for 'bearings{2,3,4}'.

```
## for the getAngle function to work later, we need a 4 character Azimuth from the tree bearings and bearing direction
ind$bearings1 <- c(paste0(as.character(ind$bearing),  as.character(ind$bearingdir)))
```

@Kah5 can you look and just make sure that the code that creates "bearings{1,2,34}" in 'ind' and 'il' is actually not needed?

**Comment by paciorek** [comment]
bearingdir only contains E, W, 88888, 99999. Just want to check this is expected.

**Comment by jpeters7** [comment]
Yep!  This is correct.

**Comment by paciorek** [comment]
Right now we have cases like:
bearing = 88888
bearingdir = E
or
bearing = W
bearingdir = 99999

Currently code is setting these to NA, just want to make sure that is correct.

**Comment by paciorek** [comment]
@Kah5 to fix get_angle_IN and deal with soMI; this is now ok in cjp_cleanup branch for IL/IN.

**Comment by Kah5** [comment]
fixed get_angle_IN and I don't think we need to worry about bearings and directions for soMI, since there are already 360 deg. azimuths in the southern michigan dataset (az_360 columns). However, we should check in with @SimonGoring @jpeters7 and Charlie about how/where these azimuths are generated.

**Comment by jpeters7** [comment]
the az_360 columns were calculated using the quadrant and the az_x (x = 1:4), values. 
 e.g., if the quadrant number was 1, the AZ as read from the mylar maps was used as is. If the quadrant number was 2, az1_360 is 180-az1. Quadrants of 3 were 180+az1 and quadrants of 4 were 360-az1.  NOTE: Missing azimuths are listed as "0" in az_360.

**Comment by paciorek** [comment]
Do we have the actual code for that somewhere? It would be best to actually do the calculation in the code in the PLS_products repository.

**Comment by jpeters7** [comment]
No. The az_360 values were added by Charlie after he did his check of the southern Michigan data.  He described how he did the calculations and I put that in the ReadMe to describe this column.  We could take out Charlie's az_360 values and add code to do that in 1_clean_merge_point_data.R

**Comment by jpeters7** [comment]
Any quadrant >4 has az_360 of 0.  For the zeroes it is a bit more tricky.  Most of the time when q=0, az_360=0.  But there are a number of trees that Charlie determined the azimuth given the direction of travel on the cardinal direction (so the az_360 becomes 90, 180, 270 or 360).  These are ones that can't have their az_360 easily calculated... 
To give you an idea about the numbers we are looking at. For tree1 there are 998 q=0 and 776 of them have az_360=0, but there are 101 trees with az_360=90, 33 trees with az_360=180, 13 trees with az_360=270, and 75 trees with az_360=360.  If you want, I can get the breakdown of these numbers for tree2, 3 and 4 as well.  There are 396 non-zero az_360 values (with q=0) for tree2, 22 for tree3 and 22 for tree4. 
I believe the notes in the "notes" column helped Charlie determine the direction of travel, but there isn't a consistent pattern in the "notes" saying what the specific direction of travel is and how that relates to the azimuth.
For simplicity, we may want to go with Charlie's az_360 values.  Or if we wanted to be more transparent, we could add a column for direction of travel and for the q=0, az_360 entries with values 90, 180, 270, or 360, I could put in the direction I read from the "notes" and then run that by Charlie to make sure I got that information correct.

**Comment by paciorek** [comment]
Ok, I guess let's leave as is, given it's not a fully automated process.
